authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = "authentication"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='authentication/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='blog:home'), name='logout'), # it is not working
    # User profile
    path('profile/', views.profile, name='profile'),
]

""" 
- The LoginView is associated with the /login/ URL and uses the login.html
    template for rendering the login form.
- The LogoutView is associated with the /logout/ URL and redirects to the 
    home page (next_page='home') after the user logs out.
"""

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    # list of posts
    path('', views.home, name='home'),
    # details of a post
    path('post_detail/<int:pk>/',
         views.post_detail, name='post_detail'),
    # create a post
    path('post_create/', views.post_create, name='post_create'),
    # edit a post
    path('post_edit/<int:pk>/',
         views.post_edit, name='post_edit'),
    # detail of a post
    path('post_detail/<int:pk>/',
         views.post_edit, name='post_detail'),
    # create a post
    path('post_create/', views.post_create, name='post_create'),
    # delete a post
    path('post_delete/<int:pk>/',
         views.post_delete, name='post_delete'),
    
    
    # details of a category
    path('category_detail/<int:pk>/',
         views.category_detail, name='category_detail'),
    # filter by tag
    path('tag_detail/<int:pk>/',
         views.tag_detail, name='tag_detail'),
    path('search_post/', views.search_post, name='search_post'),
    
#     
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('authentication/', include('authentication.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# create a model for the user profile
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_picture = models.ImageField(upload_to='media/', blank=True)
    biography = models.TextField(blank=True)

    def __str__(self):
        return self.user.username

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

# form to create a user profile
""" 
UserProfileForm is responsible for updating the profile-specific fields like
the profile picture and biography
"""

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'biography']


""" 
UserForm is used to update the user's general information such as first name,
last name, and email.
"""

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

authentication/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from blog.models import *

from .forms import UserProfileForm, UserForm
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('blog:home')  
    else:
        form = UserCreationForm()
    return render(request, 'authentication/register.html', {'form': form})

""" 
- The view checks if the request method is POST. If it is, 
the registration form is submitted, and the form data is processed.
- The `UserCreationForm` is instantiated with the POST data. If the 
form is valid, a new user is created and saved to the database using `form.save()`.
- The user is then logged in using `login(request, user)` 
to establish the user's session.
- Finally, the user is redirected to the home page.
"""

""" 
The profile view is responsible for displaying and updating the user profile. 
If the request method is POST, it processes the form data and saves the updated 
user and profile information. If the request method is GET, it retrieves the 
user and profile forms with the current user's data.

"""


@login_required
def profile(request):
    # get the list of all of this user posts
    posts = Post.objects.filter(author=request.user)
    
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user)

        if   profile_form.is_valid():
            # if user_form.is_valid() and profile_form.is_valid()
            #user_form.save()
            print(profile_form)
    
            profile_form.save()
            return redirect('authentication:profile')
        """ 
        It does not save the profile_form values but it saves the user_form values
        work on saving the profile pic and the biagraphy of the user
        """
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'current_user': request.user,
        'posts': posts,
    }

    return render(request, 'authentication/profile.html', context)

templates/authentication/login.html
{% extends "home.html" %} 

{% block content %}

<h2>Login</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Login</button>
</form>

{% endblock content %}

templates/authentication/logout.html
{% extends "home.html" %}

{% block content %}

  
<h2>Logout</h2>
<p>You have been logged out.</p>

{% endblock content %}

templates/authentication/profile.html
{% extends "home.html" %}

{% block content %}
<p><a href="{% url 'blog:post_create' %}">Create a Post?</a></p>

<ul>
    <li><p>{{ current_user.username }}</p></li>
    <li><p>{{ current_user.first_name }}</p></li>
    <li><p>{{ current_user.last_name }}</p></li>
</ul>

{% if posts %}
    
    {% for post in posts %}
    <div class="post">

        <h3><a href="{% url  'blog:post_detail' post.pk %}">{{ post.title }} </a> on {{ post.publication_date }}</h3>
        
        <span
          >Tags: {% for tag in post.tags.all %}
          <a href="{% url  'blog:tag_detail' tag.pk %}">{{tag.name}}</a> {% if not forloop.last %}, {% endif %} {% endfor %}
        </span>
      </div>
    {% endfor %}
        
{% endif %}
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <button type="submit">Update Profile</button>
    </form>

{% endblock content %}

templates/authentication/register.html
{% extends "home.html" %}


{% block content %}

<!-- register.html -->
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>


{% comment %} In this example, the `form.as_p` template variable renders the registration form fields as paragraphs (`<p>` tags). You can modify the template to fit your desired form layout. {% endcomment %}
    
{% endblock content %}
    