authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = "authentication"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='authentication/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='blog:home'), name='logout'), # it is not working
    # User profile
    path('profile/', views.profile, name='profile'),
]

""" 
- The LoginView is associated with the /login/ URL and uses the login.html
    template for rendering the login form.
- The LogoutView is associated with the /logout/ URL and redirects to the 
    home page (next_page='home') after the user logs out.
"""

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    # list of posts
    path('', views.home, name='home'),
    # details of a post
    path('post_detail/<int:pk>/',
         views.post_detail, name='post_detail'),
    # create a post
    path('post_create/', views.post_create, name='post_create'),
    # edit a post
    path('post_edit/<int:pk>/',
         views.post_edit, name='post_edit'),
    # detail of a post
    path('post_detail/<int:pk>/',
         views.post_edit, name='post_detail'),
    # create a post
    path('post_create/', views.post_create, name='post_create'),
    # delete a post
    path('post_delete/<int:pk>/',
         views.post_delete, name='post_delete'),
    
    
    # details of a category
    path('category_detail/<int:pk>/',
         views.category_detail, name='category_detail'),
    # filter by tag
    path('tag_detail/<int:pk>/',
         views.tag_detail, name='tag_detail'),
    path('search_post/', views.search_post, name='search_post'),
    
#     
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('authentication/', include('authentication.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <title>Your Website Name</title>
    <style>
      body {
        font-family: "Arial", sans-serif;
        background-color: #ffffff;
        color: #000000;
      }

      header {
        background-color: #eaceeb;
        color: #ffffff;
        padding: 20px;
      }

      nav {
        display: flex;
        justify-content: space-between;
        align-items: center;
      }

      nav ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        display: flex;
      }

      nav ul li {
        margin-right: 20px;
      }

      nav ul li a {
        color: #ffffff;
        text-decoration: none;
      }

      #banner {
        background-image: url("path/to/banner-image.jpg");
        background-size: cover;
        height: 300px;
        display: flex;
        justify-content: center;
        align-items: center;
      }

      #banner h1 {
        font-size: 36px;
        font-weight: bold;
        color: #eaceeb;
        text-align: center;
      }

      #categories {
        background-color: #ffffff;
        padding: 20px;
      }

      #categories h2 {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 20px;
      }

      .dropdown-menu {
        display: none;
        position: absolute;
        background-color: #eaceeb;
        padding: 10px;
        list-style-type: none;
        margin: 0;
      }

      .dropdown:hover .dropdown-menu {
        display: block;
      }

      .dropdown-menu li {
        margin-bottom: 5px;
      }

      .dropdown-menu li a {
        color: #ffffff;
        text-decoration: none;
      }

      .category-list {
        display: flex;
        justify-content: center;
        align-items: center;
      }

      .category-list a{
        display: block;
        padding: 10px 20px;
        margin: 0 10px;
        background-color: #eaceeb;
        color: #ffffff;
        text-decoration: none;
        font-weight: bold;
        border-radius: 20px;
      }

      .category-list form{
        display: block;
        padding: 10px 20px;
        margin: 0 10px;
        background-color: #eaceeb;
        color: #ffffff;
        text-decoration: none;
        font-weight: bold;
        border-radius: 20px;
      }

      #latest-posts {
        background-color: #ffffff;
        padding: 20px;
      }

      #latest-posts h2 {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 20px;
      }

      .post {
        margin-bottom: 20px;
      }

      .post h3 {
        font-size: 20px;
        font-weight: bold;
        margin-bottom: 10px;
      }

      .post p {
        margin-bottom: 10px;
      }

      footer {
        background-color: #eaceeb;
        color: #ffffff;
        padding: 20px;
        text-align: center;
      }

      footer p {
        margin: 0;
      }
    </style>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          <li><a href="{% url  'blog:home' %}">Home</a></li>

          <li class="dropdown">
            <a href="#">Categories</a>
            <ul class="dropdown-menu">
              {% for category in categories %}
              <li>
                <a href="{% url  'blog:category_detail' category.pk %}"
                  >{{ category.name }}</a
                >
              </li>
              {% endfor %}
            </ul>
          </li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
          
          {% if user %}
          <li> Hi <a href="{% url 'authentication:profile' %}">{{user.username}}</a>!!</li>
          <li><a href="{% url 'authentication:logout' %}">Logout?</a></li>
          {% else %}
          <li><a href="#">Login</a></li>
          {% endif %}
            
        </ul>
      </nav>
    </header>

    <section id="banner">
      <h1>Welcome to Joseline's Insights</h1>
    </section>

    {% if categories %}

    <section id="categories">
      <h2>Categories</h2>
      <div class="category-list">
        {% for category in categories %}
        <a href="{% url  'blog:category_detail' category.pk %}"
          >{{category.name}}</a
        >
        {% endfor %}
      </div>
    </section>

    {% endif %} 
    
    {% block content %}

    <div id="categories" class="category-list">
      <form action="{% url 'blog:search_post' %}" method="GET">
        <input
          type="text"
          id="post"
          name="post"
          placeholder="Search a post with keywords?!"
        
        />

        <input
                type="text"
                id="category"
                name="category"
                placeholder="Search by category?"
              />
        <button type="submit">Search</button>
      </form>
    </div>

    <section id="latest-posts">
      <h2>Latest Posts</h2>

      {% for post in posts %}

      <div class="post">

        <h3><a href="{% url  'blog:post_detail' post.pk %}">{{ post.title }} </a> on {{ post.publication_date }}</h3>
        <p>{{post.content}}</p>
        <span
          >Tags: {% for tag in post.tags.all %}
          <a href="{% url  'blog:tag_detail' tag.pk %}">{{tag.name}}</a> {% if not forloop.last %}, {% endif %} {% endfor %}
        </span>
      </div>

      {% endfor %}
    </section>

    {% comment %} <form action="{% url 'blog:filter_by_category' 0 %}" method="GET">
      <select name="category">
        <option value="0">All Categories</option>
        {% for category in categories %}
        <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
      </select>
      <button type="submit">Filter</button>
    </form>

    <form action="{% url 'blog:filter_by_tag' 0 %}" method="GET">
      <select name="tag">
        <option value="0">All Tags</option>
        {% for tag in tags %}
        <option value="{{ tag.id }}">{{ tag.name }}</option>
        {% endfor %}
      </select>
      <button type="submit">Filter</button>
    </form>

    <ul>
      {% for blog_post in posts %}
      <li>
        <h3>{{ blog_post.title }}</h3>
        <p>{{ blog_post.content }}</p>
        <p>Category: {{ blog_post.category.name }}</p>
        <p>
          Tags: {% for tag in blog_post.tags.all %}{{ tag.name }}{% if not
          forloop.last %}, {% endif %}{% endfor %}
        </p>
      </li>

      {% endfor %}
    </ul>  {% endcomment %}
    {% endblock content %}
    
    <footer>
      <p>&copy; 2023 Joseline's Insights. All rights reserved.</p>
    </footer>
  </body>
</html>